### ISSUE TITLE
it crashes on mac

### ISSUE THREAD

**Issue by warycat** [emmanueltouzery/cigale#3]
thread 'main' panicked at 'loading icon: Error { domain: gdk-pixbuf-error-quark, code: 3, message: "Unrecognized image file format" }', src/libcore/result.rs:1188:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: cigale::icons::load_pixbuf
  10: <cigale::widgets::datepicker::DatePicker as relm::widget::Widget>::view
  11: relm::create_widget
  12: <W as relm::container::ContainerWidget>::add_widget
  13: <cigale::widgets::events::EventView as relm::widget::Widget>::view
  14: relm::create_widget
  15: <W as relm::container::ContainerWidget>::add_widget
  16: <cigale::widgets::win::Win as relm::widget::Widget>::view
  17: relm::run
  18: cigale::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: std::rt::lang_start_internal
  23: main

**Comment by emmanueltouzery** [comment]
hmm, strange. the icons are SVG that get embedded in the binary. It could be that embedding in the binary or reading from the binary or SVG decoding doesn't work.

Since you're on mac, you must have built from source. I just pushed a new branch `icons` in which I print to stdout the icon contents before attempting to display them. The intent is to track down which bit goes wrong. On my machine when I start the app, I see valid SVG on the terminal, that is:

```
$ cargo run
   Compiling cigale v0.2.0 (/home/emmanuel/home/cigale)
    Finished dev [unoptimized + debuginfo] target(s) in 11.37s
     Running `target/debug/cigale`
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 512\"><path d=\"M31.7 239l136-136c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9L127.9 256l96.4 96.4c9.4 9.4 9.4 24.6 0 33.9L201.7 409c-9.4 9.4-24.6 9.4-33.9 0l-136-136c-9.5-9.4-9.5-24.6-.1-34z\"/></svg>"
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 448 512\"><path d=\"M0 464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V192H0v272zm320-196c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM192 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM64 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zM400 64h-48V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H160V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H48C21.5 64 0 85.5 0 112v48h448v-48c0-26.5-21.5-48-48-48z\"/></svg>"
...
```
Can you do:

```
git pull
git checkout icons
cargo run
```

in a terminal and report the output?

**Comment by dxps** [comment]
Hi Emmanuel,

First of all, in order to be able to compile it (i.e. get rid off `ld: library not found for -lgtk-3` issue), I had to install `gtk-3` using `brew install gtk+3`.

Then I tried your advice and ran it from `icons` branch, but without much success:
```
> cargo run
   Compiling cigale v0.2.0 (/Users/.../cigale)
    Finished dev [unoptimized + debuginfo] target(s) in 9.03s
     Running `target/debug/cigale`
Warning: Failed to set locale category LC_NUMERIC to en_RO.
Warning: Failed to set locale category LC_TIME to en_RO.
Warning: Failed to set locale category LC_COLLATE to en_RO.
Warning: Failed to set locale category LC_MONETARY to en_RO.
Warning: Failed to set locale category LC_MESSAGES to en_RO.
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 512\"><path d=\"M31.7 239l136-136c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9L127.9 256l96.4 96.4c9.4 9.4 9.4 24.6 0 33.9L201.7 409c-9.4 9.4-24.6 9.4-33.9 0l-136-136c-9.5-9.4-9.5-24.6-.1-34z\"/></svg>"
thread 'main' panicked at 'loading icon: Error { domain: gdk-pixbuf-error-quark, code: 3, message: "Unrecognized image file format" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
```

Hope it helps.
Thanks.

**Comment by emmanueltouzery** [comment]
Makes sense that you must install gtk3 yes.

And what you pasted helps yes. I see that the SVG which is contained in the binary is properly read. So now the question is why gdk-pixbuf cannot decode a valid SVG.

Can you please install librsvg too:
https://formulae.brew.sh/formula/librsvg

    brew install librsvg

I think this will possibly also register the gdk-pixbuf SVG loader and fix the issue. Let me know!

**Comment by dxps** [comment]
Thanks for the feedback! Indeed, installing also `librsvg` solved the issue.

Now it runs on both `master` and `icons` branches, but the icons are not shown:

![image](https://user-images.githubusercontent.com/14140226/76348569-14a25c00-6311-11ea-87fb-9c17e868a384.png)

And running from `icons` branch, the following was logged to the standard output (which is what you put at icons.rs:23):
```
cargo run
   Compiling cigale v0.2.0 (/Users/.../cigale)
    Finished dev [unoptimized + debuginfo] target(s) in 18.10s
     Running `target/debug/cigale`
Warning: Failed to set locale category LC_NUMERIC to en_RO.
Warning: Failed to set locale category LC_TIME to en_RO.
Warning: Failed to set locale category LC_COLLATE to en_RO.
Warning: Failed to set locale category LC_MONETARY to en_RO.
Warning: Failed to set locale category LC_MESSAGES to en_RO.
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 512\"><path d=\"M31.7 239l136-136c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9L127.9 256l96.4 96.4c9.4 9.4 9.4 24.6 0 33.9L201.7 409c-9.4 9.4-24.6 9.4-33.9 0l-136-136c-9.5-9.4-9.5-24.6-.1-34z\"/></svg>"
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 448 512\"><path d=\"M0 464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V192H0v272zm320-196c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM192 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM64 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zM400 64h-48V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H160V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H48C21.5 64 0 85.5 0 112v48h448v-48c0-26.5-21.5-48-48-48z\"/></svg>"
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 512\"><path d=\"M224.3 273l-136 136c-9.4 9.4-24.6 9.4-33.9 0l-22.6-22.6c-9.4-9.4-9.4-24.6 0-33.9l96.4-96.4-96.4-96.4c-9.4-9.4-9.4-24.6 0-33.9L54.3 103c9.4-9.4 24.6-9.4 33.9 0l136 136c9.5 9.4 9.5 24.6.1 34z\"/></svg>"
icons bytes: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg\n   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n   xmlns:cc=\"http://creativecommons.org/ns#\"\n   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n   xmlns:svg=\"http://www.w3.org/2000/svg\"\n   xmlns=\"http://www.w3.org/2000/svg\"\n   xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n   width=\"48px\"\n   height=\"48px\"\n   id=\"svg2826\"\n   version=\"1.1\"\n   inkscape:version=\"1.0beta2 (unknown)\"\n   sodipodi:docname=\"cigale2.svg\">\n  <defs\n     id=\"defs2828\">\n    <linearGradient\n       inkscape:collect=\"always\"\n       id=\"linearGradient897\">\n      <stop\n         style=\"stop-color:#fafafa;stop-opacity:1\"\n         offset=\"0\"\n         id=\"stop893\" />\n      <stop\n         style=\"stop-color:#f6f5f4;stop-opacity:1\"\n         offset=\"1\"\n         id=\"stop895\" />\n    </linearGradient>\n    <linearGradient\n       id=\"linearGradient3967\">\n      <stop\n         style=\"stop-color:#000000;stop-opacity:0;\"\n         offset=\"0\"\n         id=\"stop3969\" />\n      <stop\n         style=\"stop-color:#000000;stop-opacity:0;\"\n         offset=\"1\"\n         id=\"stop3971\" />\n    </linearGradient>\n    <inkscape:perspective\n       sodipodi:type=\"inkscape:persp3d\"\n       inkscape:vp_x=\"0 : 24 : 1\"\n       inkscape:vp_y=\"0 : 1000 : 0\"\n       inkscape:vp_z=\"48 : 24 : 1\"\n       inkscape:persp3d-origin=\"24 : 16 : 1\"\n       id=\"perspective2834\" />\n    <radialGradient\n       inkscape:collect=\"always\"\n       xlink:href=\"#linearGradient897\"\n       id=\"radialGradient903\"\n       gradientUnits=\"userSpaceOnUse\"\n       cx=\"-9.0113535\"\n       cy=\"14.238262\"\n       fx=\"-9.0113535\"\n       fy=\"14.238262\"\n       r=\"10.160351\"\n       gradientTransform=\"matrix(0.90796687,0,0,0.89328936,29.218934,9.1024296)\" />\n  </defs>\n  <sodipodi:namedview\n     id=\"base\"\n     pagecolor=\"#ffffff\"\n     bordercolor=\"#666666\"\n     borderopacity=\"1.0\"\n     inkscape:pageopacity=\"0.0\"\n     inkscape:pageshadow=\"2\"\n     inkscape:zoom=\"3.2770353\"\n     inkscape:cx=\"54.78281\"\n     inkscape:cy=\"37.622539\"\n     inkscape:current-layer=\"layer1\"\n     showgrid=\"true\"\n     inkscape:grid-bbox=\"true\"\n     inkscape:document-units=\"px\"\n     inkscape:window-width=\"1916\"\n     inkscape:window-height=\"829\"\n     inkscape:window-x=\"1920\"\n     inkscape:window-y=\"18\"\n     inkscape:window-maximized=\"0\"\n     inkscape:document-rotation=\"0\" />\n  <metadata\n     id=\"metadata2831\">\n    <rdf:RDF>\n      <cc:Work\n         rdf:about=\"\">\n        <dc:format>image/svg+xml</dc:format>\n        <dc:type\n           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n        <dc:title></dc:title>\n      </cc:Work>\n    </rdf:RDF>\n  </metadata>\n  <g\n     id=\"layer1\"\n     inkscape:label=\"Layer 1\"\n     inkscape:groupmode=\"layer\">\n    <rect\n       style=\"fill:#1a5fb4;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.254844;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1\"\n       id=\"rect3615\"\n       width=\"28.971817\"\n       height=\"34.993382\"\n       x=\"13.227469\"\n       y=\"6.7181029\"\n       rx=\"1.1338583\" />\n    <rect\n       y=\"6.2687497\"\n       x=\"12.637547\"\n       height=\"34.993382\"\n       width=\"28.971817\"\n       id=\"rect3617\"\n       style=\"fill:#0000d5;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.254844;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1\"\n       rx=\"1.1338583\" />\n    <path\n       style=\"fill:#ffffff;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.834299\"\n       d=\"m 13.809201,40.029922 c 8.811989,0 17.623978,0 26.435966,0 0,-10.896816 0,-21.793632 0,-32.6904477 -8.811988,0 -17.623977,0 -26.435966,0 0,10.8968157 0,21.7936317 0,32.6904477 z\"\n       id=\"rect2836\"\n       inkscape:connector-curvature=\"0\" />\n    <path\n       style=\"fill:#1c71d8;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.254844;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:1\"\n       d=\"M 12.026994,5.7632273 H 40.998811 C 39.697177,19.210962 38.082361,31.902365 34.878642,40.756607 H 5.906825 C 8.9153142,29.922024 10.761894,18.09177 12.026994,5.7632273 Z\"\n       id=\"rect3610\"\n       sodipodi:nodetypes=\"ccccc\"\n       inkscape:connector-curvature=\"0\" />\n    <path\n       style=\"fill:#ffffff;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.834299\"\n       d=\"M 13.608463,8.2241384 C 12.497532,18.626596 10.864711,28.982304 8.2172129,39.187385 c 8.4309971,0 16.8619931,0 25.2929901,0 3.315867,-10.369042 4.335854,-21.145873 5.47728,-31.8479107 -8.430997,0 -16.861993,0 -25.29299,0 l -0.0762,0.7836518 -0.0098,0.1010123 z\"\n       id=\"path5059\"\n       inkscape:connector-curvature=\"0\" />\n    <rect\n       style=\"fill:#62a0ea;fill-opacity:1;stroke:#000000;stroke-width:0.191775;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1\"\n       id=\"rect4012\"\n       width=\"26.892862\"\n       height=\"5.6086092\"\n       x=\"13.884035\"\n       y=\"6.5604258\"\n       ry=\"2.0277808\"\n       transform=\"matrix(1,0,-0.12714463,0.99188419,0,0)\" />\n    <rect\n       y=\"30.665394\"\n       x=\"12.972034\"\n       height=\"0.44934997\"\n       width=\"20.450699\"\n       id=\"rect5074\"\n       style=\"fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.834299\" />\n    <rect\n       style=\"fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.834299\"\n       id=\"rect5076\"\n       width=\"20.450699\"\n       height=\"0.44934997\"\n       x=\"14.234079\"\n       y=\"24.907335\" />\n    <rect\n       y=\"19.266209\"\n       x=\"14.958502\"\n       height=\"0.44934997\"\n       width=\"20.450699\"\n       id=\"rect5078\"\n       style=\"fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.834299\" />\n    <g\n       transform=\"matrix(1.0749507,0,0,1.0749507,1.8764696,0.40204623)\"\n       id=\"g929\">\n      <ellipse\n         ry=\"8.6294889\"\n         rx=\"8.7712784\"\n         id=\"path3197\"\n         style=\"fill:url(#radialGradient903);fill-opacity:1;stroke:#000000;stroke-width:0.900598;stroke-opacity:1\"\n         cx=\"24.644957\"\n         cy=\"24.185953\" />\n      <ellipse\n         cy=\"23.968336\"\n         cx=\"24.483276\"\n         style=\"fill:none;fill-opacity:1;stroke:#f5c211;stroke-width:0.900598;stroke-opacity:1\"\n         id=\"ellipse929\"\n         rx=\"8.7712784\"\n         ry=\"8.6294889\" />\n      <path\n         inkscape:connector-curvature=\"0\"\n         id=\"path923\"\n         d=\"m 30.953634,32.195271 8.032234,9.523974\"\n         style=\"fill:#f5c211;stroke:#000000;stroke-width:2.7;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1\" />\n      <path\n         style=\"fill:#f5c211;stroke:#f5c211;stroke-width:2.7;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1\"\n         d=\"m 31.060708,31.892807 8.032234,9.523974\"\n         id=\"path921\"\n         inkscape:connector-curvature=\"0\" />\n    </g>\n  </g>\n</svg>\n"
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 384 512\"><path d=\"M384 144c0-44.2-35.8-80-80-80s-80 35.8-80 80c0 36.4 24.3 67.1 57.5 76.8-.6 16.1-4.2 28.5-11 36.9-15.4 19.2-49.3 22.4-85.2 25.7-28.2 2.6-57.4 5.4-81.3 16.9v-144c32.5-10.2 56-40.5 56-76.3 0-44.2-35.8-80-80-80S0 35.8 0 80c0 35.8 23.5 66.1 56 76.3v199.3C23.5 365.9 0 396.2 0 432c0 44.2 35.8 80 80 80s80-35.8 80-80c0-34-21.2-63.1-51.2-74.6 3.1-5.2 7.8-9.8 14.9-13.4 16.2-8.2 40.4-10.4 66.1-12.8 42.2-3.9 90-8.4 118.2-43.4 14-17.4 21.1-39.8 21.6-67.9 31.6-10.8 54.4-40.7 54.4-75.9zM80 64c8.8 0 16 7.2 16 16s-7.2 16-16 16-16-7.2-16-16 7.2-16 16-16zm0 384c-8.8 0-16-7.2-16-16s7.2-16 16-16 16 7.2 16 16-7.2 16-16 16zm224-320c8.8 0 16 7.2 16 16s-7.2 16-16 16-16-7.2-16-16 7.2-16 16-16z\"/></svg>"
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path d=\"M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z\"/></svg>"
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 448 512\"><path d=\"M0 464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V192H0v272zm320-196c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM192 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM64 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zM400 64h-48V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H160V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H48C21.5 64 0 85.5 0 112v48h448v-48c0-26.5-21.5-48-48-48z\"/></svg>"
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path d=\"M139.61 35.5a12 12 0 0 0-17 0L58.93 98.81l-22.7-22.12a12 12 0 0 0-17 0L3.53 92.41a12 12 0 0 0 0 17l47.59 47.4a12.78 12.78 0 0 0 17.61 0l15.59-15.62L156.52 69a12.09 12.09 0 0 0 .09-17zm0 159.19a12 12 0 0 0-17 0l-63.68 63.72-22.7-22.1a12 12 0 0 0-17 0L3.53 252a12 12 0 0 0 0 17L51 316.5a12.77 12.77 0 0 0 17.6 0l15.7-15.69 72.2-72.22a12 12 0 0 0 .09-16.9zM64 368c-26.49 0-48.59 21.5-48.59 48S37.53 464 64 464a48 48 0 0 0 0-96zm432 16H208a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h288a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16zm0-320H208a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h288a16 16 0 0 0 16-16V80a16 16 0 0 0-16-16zm0 160H208a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h288a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16z\"/></svg>"
icons bytes: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path d=\"M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z\"/></svg>"
```

**Comment by emmanueltouzery** [comment]
alright, we're gonna make this work :-)
and then i'll add OSX instructions on the cigale page. I think you need to install the adwaita theme on brew too to get the gtk icons.

Please try:

    brew install adwaita-icon-theme

https://formulae.brew.sh/formula/adwaita-icon-theme

**Comment by emmanueltouzery** [comment]
(it's not clear to me why installing gtk doesn't install these things out of the box...)

**Comment by dxps** [comment]
Hooray! Thanks for all the help! And congrats for the result! 😄 

![image](https://user-images.githubusercontent.com/14140226/76350714-e4f55300-6314-11ea-8613-b34cdd9d36ed.png)

Indeed, at the end of this journey we should collect the lessons learned: some notes for MacOS platforms.

@warycat I think the issue can now be closed.

**Comment by emmanueltouzery** [comment]
I added OSX installation instructions in the README. I could also change the application to maybe react better if gdk-pixbuf cannot decode SVGs, but if people follow the instructions the point is moot I guess :-)

Thanks for the patience and I hope the app comes in handy for you!

**Comment by emmanueltouzery** [comment]
Hi, I've made a change now on how cigale loads its icons, I'd be interested if the latest master still builds and runs OK on OSX... One little worry is that it now needs the `glib-compile-resources` program to be around at compile-time. Brew should provide it, at least the 'glib' brew package (on which gtk depends upon), but I can't be 100%. Maybe the program is also available, but not in the PATH. So if we could update the OSX installation instructions, I'd be interested in your feedback.

There is also a small chance that the librsvg brew package is not needed anymore, but that's not a big thing.
